## Load Data Mr GIS

In [ ]:
import pandas as pd
dfgis=pd.read_csv('/content/drive/MyDrive/Oportunidades/Mr Gis Demograficos.csv')
dfgis.replace(',','', regex=True, inplace=True)
dfgis.replace(' -   ',0, regex=True, inplace=True) 
dfgis

              key masculino femenino  ...     D+    E nse_ponderante
0       ARTELI001    135548   145581  ...  36701  121              c
1       ARTELI002    130574   139699  ...  37280  121              c
2       ARTELI003     56651    57205  ...   2774    0             c+
3       ARTELI004     50190    50819  ...   2774    0             c+
4       ARTELI005    207388   224619  ...   4011    0              c
...           ...       ...      ...  ...    ...  ...            ...
19258  WALMEX4919       NaN      NaN  ...    NaN  NaN              c
19259  WALMEX5031       NaN      NaN  ...    NaN  NaN              c
19260  WALMEX5039       NaN      NaN  ...    NaN  NaN              c
19261  WALMEX5072       NaN      NaN  ...    NaN  NaN              c
19262  WALMEX5093       NaN      NaN  ...    NaN  NaN              c

[19263 rows x 31 columns]

## Load Cat Hiper Super

In [ ]:
dfhip=pd.read_csv('/content/drive/MyDrive/Oportunidades/catalogo_hiper_super.csv')

In [ ]:
dfhip

          Tienda Cliente4_DscNestle          Canal      Formato Macroformato
0       MERCO502        MX L4 MERCO  AUTOSERVICIOS    AS BODEGA      Express
1       MERCO582        MX L4 MERCO  AUTOSERVICIOS  SIN FORMATO      Express
2       MERCO510        MX L4 MERCO  AUTOSERVICIOS    AS BODEGA      Express
3       MERCO529        MX L4 MERCO  AUTOSERVICIOS    AS BODEGA      Express
4       MERCO566        MX L4 MERCO  AUTOSERVICIOS  SIN FORMATO      Express
...          ...                ...            ...          ...          ...
4353  WALMEX2568        MX4 WALMART  AUTOSERVICIOS          BAE      Express
4354  WALMEX3130        MX4 WALMART  AUTOSERVICIOS          BAE      Express
4355  WALMEX2975        MX4 WALMART  AUTOSERVICIOS          BAE      Express
4356  WALMEX1562        MX4 WALMART  AUTOSERVICIOS          BAE      Express
4357  WALMEX1794        MX4 WALMART  AUTOSERVICIOS          BAE      Express

[4358 rows x 5 columns]

In [ ]:
dfjoined=pd.merge(dfgis,dfhip[['Tienda','Macroformato']],left_on='key',right_on='Tienda',how='inner')
dfjoined.drop('Tienda',axis=1,inplace=True)

In [ ]:
dfjoined

             key masculino femenino  ...    E nse_ponderante Macroformato
0      ARTELI001    135548   145581  ...  121              c        Super
1      ARTELI002    130574   139699  ...  121              c        Super
2      ARTELI003     56651    57205  ...    0             c+      Express
3      ARTELI004     50190    50819  ...    0             c+        Super
4      ARTELI005    207388   224619  ...    0              c        Hiper
...          ...       ...      ...  ...  ...            ...          ...
4205  WALMEX4919       NaN      NaN  ...  NaN              c       Bodega
4206  WALMEX5031       NaN      NaN  ...  NaN              c      Express
4207  WALMEX5039       NaN      NaN  ...  NaN              c      Express
4208  WALMEX5072       NaN      NaN  ...  NaN              c      Express
4209  WALMEX5093       NaN      NaN  ...  NaN              c      Express

[4210 rows x 32 columns]

In [ ]:
dfjoined['SumaNse']= dfjoined.iloc[:,23:30].astype(float).sum(axis=1)

## Joined Data Set

In [ ]:
dfjoined

             key masculino femenino  ... nse_ponderante Macroformato   SumaNse
0      ARTELI001    135548   145581  ...              c        Super  281197.0
1      ARTELI002    130574   139699  ...              c        Super  270341.0
2      ARTELI003     56651    57205  ...             c+      Express  113957.0
3      ARTELI004     50190    50819  ...             c+        Super  101110.0
4      ARTELI005    207388   224619  ...              c        Hiper  432007.0
...          ...       ...      ...  ...            ...          ...       ...
4205  WALMEX4919       NaN      NaN  ...              c       Bodega       0.0
4206  WALMEX5031       NaN      NaN  ...              c      Express       0.0
4207  WALMEX5039       NaN      NaN  ...              c      Express       0.0
4208  WALMEX5072       NaN      NaN  ...              c      Express       0.0
4209  WALMEX5093       NaN      NaN  ...              c      Express       0.0

[4210 rows x 33 columns]

In [ ]:
dfjoined.columns

Index(['key', 'masculino', 'femenino', 'genero_ponderante', '0a2', '3a5',
       '6a11', '12a14', '15a17', '18a24', '25a40', '41a50', '51a60', '61a70',
       'mayor70', 'poblacion_total', 'poblacion_ponderante', 'pea', 'poc',
       'vivienda_total', 'hogar_total', 'ingreso_diario', 'ingreso_mensual',
       'AB', 'C', 'C-', 'C+', 'D', 'D+', 'E', 'nse_ponderante', 'Macroformato',
       'SumaNse'],
      dtype='object')

# load Data of Products

In [ ]:
import numpy as np
dfproduct=pd.read_csv('/content/drive/MyDrive/Oportunidades/Products_completo.csv')
dfproduct.replace('Preferente','SI', regex=True, inplace=True)
dfproduct.replace('Si','SI', regex=True, inplace=True)
dfproduct.replace('Sí','SI', regex=True, inplace=True)
dfproduct.rename(columns={"2a14": "12a14"},inplace=True)
dfproduct.drop(columns=['SAP','UPC Unidad de venta','Gr./ Ml','Unidad Gr.'],inplace=True)
dfproduct

                                      Descripción Lean  ... Express
0                                 La Lecherita 100 Grs  ...      SI
1                            Lechera SIrve Fácil 335Gr  ...      No
2                   Lechera SIrve Fácil Dulde De Leche  ...      No
3                     La Lechera SIrve Fácil Chocolate  ...      No
4                              La Lechera Lata 375 Grs  ...      SI
..                                                 ...  ...     ...
966        COCINA - NUEZ DE CASTILLA SELECCIONADA 16 U  ...      NO
967                                       Golden latte  ...      NO
968                                       Matcha Latte  ...      NO
969                                        Cacao Latte  ...      NO
970  NH CLUBES - PACK FUNCIONALES SNACK REFRESH 12 ...  ...      NO

[971 rows x 27 columns]

In [ ]:
laliprod=dfproduct['Descripción Lean'].unique().tolist()

## Searching parameters for $[P]$ in $[S]$
### Normalize Formula for Rank:
#### $$\tilde{x}_i = \frac{x_i - x_{min}}{x_{max} - x_{min}}$$

In [ ]:
lidf=[]
for x in laliprod:
  dfprod=dfproduct[dfproduct['Descripción Lean']==x]
  row = 0                                                                                                                                                                                     
  valmac ='SI'
  list_macro = [c for c in dfprod.columns if dfprod[c].iloc[row] == valmac]                                                                                                                                   
  filtered_macro = dfprod[list_macro]                                                                                                                                                                  
  lasmacro=filtered_macro.columns.tolist()                                                                                                                                                                                    
  value = 1                                                                                                                                                                                
  list_comp = [c for c in dfprod.columns if dfprod[c].iloc[row] == value]                                                                                                                                   
  filtered_df = dfprod[list_comp]                                                                                                                                                                  
  lascol=filtered_df.columns.tolist()
  edad=[]
  nse=[]
  for r in lascol:
    if r in [ '0a2', '3a5','6a11', '12a14', '15a17', '18a24', '25a40', '41a50', '51a60', '61a70','mayor70']:
      edad.append(r)
    else:
      nse.append(r)
  dfsumedad=dfjoined[edad]
  dfsumnse=dfjoined[nse]

  dfsumedad['Ponderar_edad']= dfsumedad.iloc[:,:].astype(float).sum(axis=1)
  dfsumnse['Ponderar_nse']= dfsumnse.iloc[:,:].astype(float).sum(axis=1)
          
  dfjoined['Ponderar_edad']=dfsumedad['Ponderar_edad']
  dfjoined['Ponderar_nse']=dfsumnse['Ponderar_nse']
  df_final=dfjoined[['key','poblacion_total', 'Macroformato',
        'SumaNse', 'Ponderar_edad', 'Ponderar_nse']]
  def comprueba(fila):
    if fila.Macroformato in lasmacro and (fila.SumaNse>0 and float(fila.poblacion_total)>0) : 
      pond_nse=(fila.Ponderar_nse*50)/float(fila.SumaNse)
      pond_pob=(fila.Ponderar_edad*50)/float(fila.poblacion_total)
      prom_pond=(pond_nse+pond_pob)/2
    else:
      prom_pond=0
    return prom_pond

  df_final['prom_pond']=df_final.apply(comprueba,axis=1)
  df_final['Normalizacion']=1+(((df_final['prom_pond']-df_final['prom_pond'].min())*(5-1))/(df_final['prom_pond'].max()-df_final['prom_pond'].min()))
  df_final['Normalizacion'] = df_final['Normalizacion'].replace(np.nan, 1)
  df_final['rank']=df_final.Normalizacion.astype(str).str[0:1]
  df_final['Descripción Lean']=dfprod['Descripción Lean'].iloc[0]
  df_final['Descripción SAP']=dfprod['Descripción SAP'].iloc[0]
  df_final['Categoría']=dfprod['Categoría'].iloc[0]
  df_final['Marca']=dfprod['Marca'].iloc[0]
  df_final['UPC x Fracción']=dfprod['UPC x Fracción'].iloc[0]
  df_final.columns=['Tienda', 'poblacion_total', 'Macroformato', 'Total_Nse', 'Suma_interes_edad',
        'Suma_interes_Nse', 'prom_pond', 'Normalizacion', 'rank',
        'Descripción Lean', 'Descripción SAP', 'Categoría', 'Marca','UPC x Fracción']

  lidf.append(df_final)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

### Proof of Concept

In [ ]:
df_sequedas[df_sequedas['Descripción SAP']=='NESCAFE DOLCE GUSTO Esp 16Cap 3x88g XR']

          Tienda poblacion_total  ...                         Marca  UPC x Fracción
0      ARTELI001          281197  ...  Cápsulas Nescafé Dolce Gusto   7613037926132
1      ARTELI002          270341  ...  Cápsulas Nescafé Dolce Gusto   7613037926132
2      ARTELI003          113957  ...  Cápsulas Nescafé Dolce Gusto   7613037926132
3      ARTELI004          101110  ...  Cápsulas Nescafé Dolce Gusto   7613037926132
4      ARTELI005          432007  ...  Cápsulas Nescafé Dolce Gusto   7613037926132
...          ...             ...  ...                           ...             ...
4205  WALMEX4919             NaN  ...  Cápsulas Nescafé Dolce Gusto   7613037926132
4206  WALMEX5031             NaN  ...  Cápsulas Nescafé Dolce Gusto   7613037926132
4207  WALMEX5039             NaN  ...  Cápsulas Nescafé Dolce Gusto   7613037926132
4208  WALMEX5072             NaN  ...  Cápsulas Nescafé Dolce Gusto   7613037926132
4209  WALMEX5093             NaN  ...  Cápsulas Nescafé Dolce Gusto   7613037926132

[4210 rows x 14 columns]

In [ ]:
df_sequedas.to_csv('/content/drive/MyDrive/Oportunidades/Output_Portfolio/busqueda_exhaustiva_pond_completo_corregido_upc.csv',index=False,encoding='utf-8-sig')